version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sarc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  serverless:
    image: node:20
    working_dir: /src
    volumes:
      - .:/src
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && NODE_ENV=development npx serverless offline"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: 